### ISSUE TITLE
SOSL search with escaped characters gets escaped again

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-ReactNative#15] opened 2016-12-26 21:54 UTC
I'm running into an issue with SOSL searches.  I want to escape special characters so that something like `-` gets replaced with `\-`.  My `replace` expression is working properly and my sosl string looks good, but it looks like the `JSON.stringify()` [here](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/blob/master/src/react.force.common.js#L36) is escaping the `\` to become `\\`, which causes the SOSL to throw an error.

```
text = text.replace(/([\?\&\|\!\{\}\[\]\(\)\^\~\*\:\\\"\'\+\-])/g, '\\$1') // escaping special SOSL characters
var sosl = 'FIND {*' + text + '*} IN ALL FIELDS RETURNING '+this.props.search+'('+this.state.returnFields+')'
forceNet.search(sosl,
  (resp) => {
    // handle response
  },
  (err) => {
    // error handling
  }
)
```

**Comment by rgoldiez** [comment] 2016-12-27 03:22
Running into the same issue trying to do a SOSL query where the `WHERE` clause is trying to match a text field.  In this case, the string to match must be enclosed in quotes, but the `JSON.stringify` is escaping the quotes and throwing a 400 error.

**Comment by huminzhi** [comment] 2017-02-22 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by ivanbogdanov** [comment] 2017-03-07 01:45
Could you give me more info on it?
what value of `text` and  `this.props.search` and `this.state.returnFields` ?

**Comment by ivanbogdanov** [comment] 2017-03-07 20:09
@rgoldiez Not able to reproduce it. Could you provide more info?

**Comment by rgoldiez** [comment] 2017-03-08 13:07
@ivanbogdanov - Sorry for the delayed response.

Suppose `text` is `52-1` <-- note the special character `-`
`this.props.search` is any object, in this case `rstk__wocst__c`
`this.state.returningFields` is any list of fields, in this case we can keep it simple `Id, Name`.

The `sosl` variable becomes this:
```
FIND {*52\-1*} IN ALL FIELDS RETURNING rstk__wocst__c(Id, Name WHERE Status_Number__c IN (3,4,5,6,7) ORDER BY LastModifiedDate DESC)
```

What's sent across the bridge it this (note the extra escape `52\\-1`:
```
SFNetReactBridge.sendRequest called: {"endPoint":"/services/data","path":"/v36.0/search","method":"GET","queryParams":{"q":"FIND {*52\\-1*} IN ALL FIELDS RETURNING rstk__wocst__c(Id, Name WHERE Status_Number__c IN (3,4,5,6,7) ORDER BY LastModifiedDate DESC)"},"headerParams":{},"fileParams":{}}
```

I'm using SDK 4.3 on this project, by the way.

**Comment by ivanbogdanov** [comment] 2017-03-08 20:23
Just verified: this issue is fixed in dev branch

**Closed** 2017-03-08 20:23 UTC
Labels: bug
