### ISSUE TITLE
SmartStore __local__, __locally_deleted__ values on Android and iOS

### ISSUE THREAD

**Issue by dborstelmann** [forcedotcom/SalesforceMobileSDK-ReactNative#34] opened 2017-08-29 19:52 UTC
When the SmartStore is init'ed, we are creating fields like so: 
```
{ path: '__locally_created__', type: 'string' },
{ path: '__locally_updated__', type: 'string' },
{ path: '__locally_deleted__', type: 'string' },
{ path: '__local__', type: 'string' },
```

Sadly, when you retrieve those values from the store and print them out, they are not equivalent on Android and iOS.

On iOS they return as string zero: `"0"`
On Android they return as string false: `"false"`

We are trying to query the smartstore based off these values and we really do not want to have to check which platform we are on every time we do that.  This also causes us other issues further down the line when deleting and editing data.

Advice? Thoughts? Solutions?

**Comment by wmathurin** [comment] 2017-08-29 20:03
The same issue has been reported on our [cordova plugin repo](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/238) (the other way to do cross-platform development with mobile sdk).

It has to do with the internal representation of booleans on iOS and Android.

There is a simple (even though not elegant) work around for correctly querying those fields in a platform safe way. See https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/238#issuecomment-264376330

**Comment by wmathurin** [comment] 2017-08-29 20:03
I'm going to close the issue here since it is a duplicate and keep the older one open.

**Closed by wmathurin** 2017-08-29 20:03 UTC

**Comment by dborstelmann** [comment] 2017-08-29 20:16
@wmathurin Thanks for the heads up.  Is there a difference between `0` and `"0"` on iOS?  Do both work or just `0`?

**Comment by wmathurin** [comment] 2017-08-29 20:23
The json object on the javascript side contains true/false.
The NSDictionary object on the objective-c side will contain 0/1 (integers) because there is no true/false in objective-c.
The indexed column will contain "0", "1" because its type (per index spec) is String.
If you use smart sql to pull the value from the index column, you get the type specified in the index spec. 

The enhancement to avoid that situation would be to introduce a new index spec type for booleans.

**Comment by dborstelmann** [comment] 2017-08-29 20:29
@wmathurin Okay thanks, one last thing, when upserting in iOS I see that setting it to `'true'` works, so I don't need to set it to `0` because of your above comment?

**Comment by wmathurin** [comment] 2017-08-29 20:35
The JSON you send in or get back should / will have boolean values.
The issue is only when you query against the indexed paths. Because the value was extracted out and cast to a string you end up with different value on iOS and Android.
That's where you want to do: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/238#issuecomment-264376330

**Comment by dborstelmann** [comment] 2017-08-29 20:58
@wmathurin Thanks for the help.
