### ISSUE TITLE
React Native Salesforce SDK login callback not received Android/iOS

### ISSUE THREAD

**Issue by vinod1988** [forcedotcom/SalesforceMobileSDK-ReactNative#352] opened 2024-01-02 18:41 UTC
Hi Team 
I am using the latest version 11.1.0 of react native sdk. I am describing the issue below 

Upon launching the app, the Salesforce login page is displayed. After entering the username and password, the app redirects to the authorization page, and although permission is granted, the expected callback is not invoked.
I am using the below functions. This is sample refe code given by the salesforce template app example

```
oauth.getAuthCredentials(
  () => that.fetchData(), // Callback for an already logged-in user
  () => {
    oauth.authenticate(
      () => that.fetchData(), // Callback upon successful authentication
      (error) => console.log('Failed to authenticate:' + error)
    );
  }
);

```
Please help me, where i am doing the mistakes

**Comment by musarratbare** [comment] 2024-01-11 07:01
Hi @vinod1988 ,

I am facing the same issue. Can you please share your workaround have researched a lot on this and I am going nowhere.

**Comment by wmathurin** [comment] 2024-04-26 20:39
This is a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/247.

**Closed by wmathurin** 2024-04-26 20:39 UTC
