### ISSUE TITLE
oauth.authenticate function not invoking success call back for SMAL based login

### ISSUE THREAD

**Issue by hmkcfs** [forcedotcom/SalesforceMobileSDK-ReactNative#365] opened 2024-04-11 16:19 UTC
Hi Team,

We integrated Azure Ad(SAML Based) with salesforce for B2B commerce login. Login is Working properly for IOS, However on android when we login oauth.authenticate not invoking success or error callback

Steps to reproduce:
1. Create a React Native project with ReactNativeDeferredTemplate
2. Create a custom login page in Azure( SMAL based login integrated with salesforce) 
3. configure custom login url in server.xml
4. Build the application
5. Click on Login button
6. SDK will open custom login page
7. login with user created for B2B standard profile 
8. Enter credential and login
9. Login Page will close automatically however it wont trigger a success callback

**Comment by wmathurin** [comment] 2024-04-26 20:37
I believe this is a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/247

**Closed by wmathurin** 2024-04-26 20:37 UTC
