### ISSUE TITLE
How to implement a sync up for a custom object ?

### ISSUE THREAD

**Issue by NadjibSb** [forcedotcom/SalesforceMobileSDK-ReactNative#230] opened 2021-06-08 08:34 UTC
is there any samples showing how to implement custom sync up target ?

**Comment by wmathurin** [comment] 2021-06-08 14:15
Closing since it's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Templates/issues/317
Also custom sync target must be implemented natively.

**Closed by wmathurin** 2021-06-08 14:15 UTC
