### ISSUE TITLE
[Android]: Bug when after comes back of background

### ISSUE THREAD

**Issue by isaac-israel-aquant** [forcedotcom/SalesforceMobileSDK-ReactNative#309] opened 2023-01-16 09:08 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 
v. 7.0 
2. Issue found in Native App or Hybrid App:
 At Hybrid App
3. OS Version:
   API 33
4. Device:
 Pixel 3A
6. Steps to reproduce:
  1.  Logout
  2. On the login screen put the app in the background 
  3.  Click on the app icon to open it 
8. Actual behavior:
  After login, the app does not navigate to the home screen (The screen that should appear after login )
10. Expected Behavior:
 After login, the app does navigate to the home screen

**Comment by wmathurin** [comment] 2023-01-17 21:10
Closing this issue since it's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2378 (that you also opened).

**Closed by wmathurin** 2023-01-17 21:10 UTC
