### ISSUE TITLE
oauth.logout() not redirecting to Login Page in iOS

### ISSUE THREAD

**Issue by bsrinath4839** [forcedotcom/SalesforceMobileSDK-ReactNative#295] opened 2022-09-13 05:34 UTC
HI,
OAuth.logout() not redirecting to Login Page instead it's landing in Allow Access Page.
Not even able to go to Login Page until or unless I close and reopen the application.

Please resolve the issue ASAP.

Thank you!

**Comment by wmathurin** [comment] 2022-09-14 16:13
Are you using advanced authentication?
Are you logging out right after logging in?

During login, there are short term cookies being setup which are not tied to the main session and are not invalidated if you logout right away. As a result, if you login then logout shortly after, you will skip the first screen where you enter your credentials and find yourself directly into the allow/deny screen.
This issue happens only when using advanced authentication, because the login flow takes place in a ASWebAuthenticationSession. With regular authentication, we use a fresh WebView every time and therefore don't have any left over cookies.

**Comment by wmathurin** [comment] 2022-09-14 16:15
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3481.

**Closed by wmathurin** 2022-09-14 16:15 UTC
