### ISSUE TITLE
File is encrypted or is not a database

### ISSUE THREAD

**Issue by mkoo21** [forcedotcom/SalesforceMobileSDK-ReactNative#26] opened 2017-05-25 20:26 UTC
We sporadically encounter this error when logging into our app via the native login screen. We can't reliably reproduce it, but it usually arises when logging out and logging back in, on both iOS and Android. Closing/reopening the app usually fixes the issue, but this does cause a crash which is far from ideal. 

Here is an example stacktrace from Android:
```
net.sqlcipher.database.SQLiteException·file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
SQLiteCompiledSql.java:-2net.sqlcipher.database.SQLiteCompiledSql.native_compile	
SQLiteCompiledSql.java:91net.sqlcipher.database.SQLiteCompiledSql.compile	
SQLiteCompiledSql.java:64net.sqlcipher.database.SQLiteCompiledSql.<init>	
SQLiteProgram.java:83net.sqlcipher.database.SQLiteProgram.<init>	
SQLiteQuery.java:49net.sqlcipher.database.SQLiteQuery.<init>	
SQLiteDirectCursorDriver.java:42net.sqlcipher.database.SQLiteDirectCursorDriver.query	
SQLiteDatabase.java:1762net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory	
SQLiteDatabase.java:1727net.sqlcipher.database.SQLiteDatabase.rawQuery	
SQLiteDatabase.java:2344net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal	
SQLiteDatabase.java:1091net.sqlcipher.database.SQLiteDatabase.openDatabase	
SQLiteDatabase.java:1154net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase	
SQLiteOpenHelper.java:162net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase	
SQLiteOpenHelper.java:129net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase	
SmartStore.java:226com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase	
SmartStoreReactBridge.java:282com.salesforce.androidsdk.reactnative.bridge.SmartStoreReactBridge.upsertSoupEntries	
Method.java:-2java.lang.reflect.Method.invoke	
Method.java:372java.lang.reflect.Method.invoke	
BaseJavaModule.java:318com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke	
JavaModuleWrapper.java:158com.facebook.react.cxxbridge.JavaModuleWrapper.invoke	
NativeRunnable.java:-2com.facebook.react.bridge.queue.NativeRunnable.run	
Handler.java:739android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
MessageQueueThreadHandler.java:31com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage	
Looper.java:145android.os.Looper.loop	
MessageQueueThreadImpl.java:196com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run	
Thread.java:818java.lang.Thread.run
```
We are using mobile SDK version 5.0.0 (with RN 0.35).

**Comment by bhariharan** [comment] 2017-05-25 22:27
@mkoo21 This typically occurs when the wrong encryption key is used to decrypt the database. It looks like your app might be trying to access `SmartStore` after logout and/or before login. Could you make sure that there are no calls that access `SmartStore` after or during logout? Also, could you upgrade to `Mobile SDK 5.1` and re-generate your app from the template?

**Comment by mkoo21** [comment] 2017-05-26 18:55
Ok, I will double check the cleanup code to make sure logout doesn't happen until after everything is complete. We register the smartstore soups in `componentDidMount` for the root component, so it's probably not that but I will keep an eye open for calls to `smartstore` when if I encounter it again. Thanks!

**Comment by mkoo21** [comment] 2017-06-20 21:21
Reopening this issue as it still appears sporadically in production. I added a whole bunch of promise chains to try and prevent any smartstore calls before login or after logout, but a few users have reported running into this error from a fresh install. 

FWIW I was able to produce a similar issue in the SmartSyncExplorer on an android physical device after logging in/out of a sandbox a couple of times; if successful, registering the contact soup will fail after login.

<img width="834" alt="screen shot 2017-06-20 at 5 11 13 pm" src="https://user-images.githubusercontent.com/12832801/27356438-7603a7aa-55dc-11e7-9dc9-0152f2849b6a.png">

**Comment by wmathurin** [comment] 2017-06-20 22:53
When you reproduced it with SmartSyncExplorer:
* what version SmartSyncExplorer of  were you using?
* what device were you running on?
* what Android OS version did it have?

Thanks.

**Comment by mkoo21** [comment] 2017-06-21 04:54
SmartSyncExplorer is version 5.1.0, a fresh clone of the master branch
Device was a samsung tab S (10.5-inch) 
The device I was using to reproduce it was running android 5, but I have seen this issue before on devices running android 6.

**Comment by booker-laputa** [comment] 2017-06-30 04:04
@mkoo21 @wmathurin 

I had this issue with iOS before.

I think the cause of it is that some of the component tried to register a soup before login.

I fix it by not rendering these component before login

**Comment by wmathurin** [comment] 2017-10-02 23:29
We fixed a decryption related bug on Android for Mobile SDK 5.3.
Let us know if you still run into that issue with Mobile SDK 5.3.

**Comment by imanmk** [comment] 2017-10-03 13:24
I'm experiencing the same issue with iOS SDK 5.3

**Comment by wmathurin** [comment] 2017-10-11 00:20
This issue has been fixed in the dev branch and will be in our next release (6.0).

**Closed by wmathurin** 2017-10-11 00:20 UTC
Labels: bug

**Comment by riquier** [comment] 2019-08-19 01:04
We have been experiencing the same issue on versions 7.0.0, 7.1.0 & 7.2.0 on Android devices (at least Android 8 + 9) on phones with arm64-v8a architecture. The login flow our app uses is based of the salesforce react native template.
