### ISSUE TITLE
SyncDowns/Ups on Parent Child?

### ISSUE THREAD

**Issue by mstohr1975** [forcedotcom/SalesforceMobileSDK-ReactNative#388] opened 2024-10-04 12:40 UTC
Hi there,

How can I trigger initial syncDown and syncUp for syncs defined in usersyncs.json, particularly parent child ones?
We did not find an example to call syncDown passing the right target and options without defining them again, but use the definition from usersyncs.json. Any examples synching multiple children?

defaultStore and soups are created, syncDown on parent works when we define a soql target once again before calling syncDown as well as reSync and syncUp.

usersyncs.json and userstore.json have been validated and loaded in AppDelegate.m via 

```
    [SFSDKAuthHelper loginIfRequired:^{
        [self setupRootViewController];
        [[MobileSyncSDKManager sharedManager] setupUserStoreFromDefaultConfig];
    }];
    return YES;
```

**Comment by wmathurin** [comment] 2024-10-04 17:33
This looks like a duplicate of: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/387
Let's continue the discussion there.

**Closed by wmathurin** 2024-10-04 17:33 UTC
